[workspace]
members = [
	"components/flubber-backend",
	"components/flubber-backend-proto",
	"components/flubber-server",
	"components/flubber-server-backend",
	"components/flubber-server-config",
	"components/flubber-server-db",
	"components/flubber-server-web",
	"components/flubber-utils"
]
