[workspace]
members = [
	"components/flubber-plugin",
	"components/flubber-plugin-proto",
	"components/flubber-server",
	"components/flubber-server-db",
	"components/flubber-server-plugin",
	"components/flubber-utils"
]
