port = 3000

[plugins.irc]
path = "./plugins/trivial/trivial.js"
args = ["--host", "acm.umn.edu", "--port", "6669"]

# path = "bash"
# args = ["-c", "./plugins/trivial/trivial.js < /dev/null; cat > /tmp/wtfmoo"]
