[database]
file = "flubber.db"

[web]
port = 8080

[backends.asdf]
cmd = "./example"
args = ["-vvv", "--debug-on-crash"]
env-file = "example.env"

[backends.asdf.env]
DEBUGGER = "gdb-network"
DEBUGGER_GDB_PORT = "12345"
